name: Milestones
main: kr.kieran.milestones.MilestonesPlugin
version: ${project.version}
author: Kieraaaan
depend: [MassiveCore]

permissions:
  # -------------------------------------------- #
  # THE REAL NODES
  # -------------------------------------------- #
  milestones.basecommand: {description: use milestones base command, default: false}
  milestones.open: {description: open the milestones gui, default: false}

  # -------------------------------------------- #
  # STAR NOTATION
  # -------------------------------------------- #
  milestones.*:
    children:
      milestones.basecommand: true
      milestones.open: true

  # -------------------------------------------- #
  # KITS
  # -------------------------------------------- #
  milestones.kit.op:
    default: op
    children:
      milestones.*: true
  milestones.kit.rank0:
    default: false
    children:
      milestones.basecommand: true
      milestones.open: true
  milestones.kit.default:
    default: true
    children:
      milestones.kit.rank0: true